language: generic

sudo: required

services:
  - docker

env:
  - AR_thumbv7m_none_eabi=arm-none-eabi-ar
  - CC_thumbv7m_none_eabi=arm-none-eabi-gcc

script:
  - bash ci.sh

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
  webhooks: http://homu.herokuapp.com/travis
