language: generic

sudo: required

services:
  - docker

script:
  - bash ci.sh

branches:
  only:
    - auto
    - try

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis
