language: generic
services: docker
sudo: required

script:
  - bash ci/script.sh

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis
